// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdlS8yCeP9Yraes2m08mRU33Nn1M5fISA',
    appId: '1:991146001519:web:b1353983cd1c87579d799a',
    messagingSenderId: '991146001519',
    projectId: 'note-taker-43c7c',
    authDomain: 'note-taker-43c7c.firebaseapp.com',
    storageBucket: 'note-taker-43c7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBog5m0_vUn7Wzwi2B6e0W2LlbqLp3fDfc',
    appId: '1:991146001519:android:2fe953961d688a149d799a',
    messagingSenderId: '991146001519',
    projectId: 'note-taker-43c7c',
    storageBucket: 'note-taker-43c7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgT6vHqTEDDLDi22Rcs4QmeFLMig1Uxo',
    appId: '1:991146001519:ios:acc8b882340cc8969d799a',
    messagingSenderId: '991146001519',
    projectId: 'note-taker-43c7c',
    storageBucket: 'note-taker-43c7c.firebasestorage.app',
    iosBundleId: 'com.example.noteTaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgT6vHqTEDDLDi22Rcs4QmeFLMig1Uxo',
    appId: '1:991146001519:ios:acc8b882340cc8969d799a',
    messagingSenderId: '991146001519',
    projectId: 'note-taker-43c7c',
    storageBucket: 'note-taker-43c7c.firebasestorage.app',
    iosBundleId: 'com.example.noteTaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdlS8yCeP9Yraes2m08mRU33Nn1M5fISA',
    appId: '1:991146001519:web:1fea69522de36dd99d799a',
    messagingSenderId: '991146001519',
    projectId: 'note-taker-43c7c',
    authDomain: 'note-taker-43c7c.firebaseapp.com',
    storageBucket: 'note-taker-43c7c.firebasestorage.app',
  );

}